import "./globals.css"

const inter = Inter({ subsets: ["latin"] })
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import { GlobalProvider } from "@/context/GlobalContext"
import { Inter } from "next/font/google"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <GlobalProvider>
      <html lang="en">
        <body className={`${inter.className} flex flex-col justify-between min-h-screen`}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </GlobalProvider>
  )
}
